resolver: lts-15.4
extra-package-dbs: []
packages:
- '.'
- 'tests/test-package/'
extra-deps:
- git: https://github.com/haskell/haddock
  commit: dae8d9de6aaf3913a3776f1af235fb72404e9970
  subdirs:
  - haddock-api
- hdocs-0.5.4.0
- direct-sqlite-2.3.26
- sqlite-simple-0.4.18.0
flags: {}
